.Dd September 12, 2024
.Dt PLAYONBSD-RS "WEB"
.Os
.Sh NAME
.Nm playonbsd-rs
.Nd official website for the playonbsd-rs project
.Sh DESCRIPTION
The playonbsd-rs project is a toy project for me to learn a bit
of rust.
At the moment, there is two projects:
.Bl -tag -width Ds
.It Lk https://pobsd.chocolatines.org the pobsd website
It provides an easy way to browse the PlayOnBSD database
.It Xr pobsd-browser 1
A terminal user interface for browsing the PlayOnBSD database
.El

